version: '3.8'

networks:
  nginx-proxy:

services:
  db:
    image: rg.fr-par.scw.cloud/db-registry-namespace/db:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      POSTGRES_DB: apigateway
      DB_HOST: db
      DB_USERNAME: admin
      DB_PASSWORD: postgres
      DB_NAME: apigateway
      DB_PORT: 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q" ]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - nginx-proxy

  api_gateway:
    image: rg.fr-par.scw.cloud/gateway-service-registry-namespace/gateway:latest
    ports:
      - "80:80"
      - "8080:80"
    environment:
      DB_HOST: db
      DB_USERNAME: admin
      DB_PASSWORD: postgres
      DB_NAME: apigateway
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nginx-proxy

  nginx:
    build: ./nginx/
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_gateway
    networks:
      - nginx-proxy

  notes_service:
    image: rg.fr-par.scw.cloud/notes-service-registry-namespace/notes:latest
    ports:
      - "50053:50053"
    environment:
      DB_HOST: db
      DB_USERNAME: admin
      DB_PASSWORD: postgres
      DB_NAME: apigateway
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nginx-proxy

  users_service:
    image: rg.fr-par.scw.cloud/users-service-registry-namespace/users:latest
    ports:
      - "50052:50052"
    environment:
      DB_HOST: db
      DB_USERNAME: admin
      DB_PASSWORD: postgres
      DB_NAME: apigateway
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nginx-proxy

  permissions_service:
    image: rg.fr-par.scw.cloud/permissions-service-registry-namespace/permissions:latest
    ports:
      - "50054:50054"
    environment:
      DB_HOST: db
      DB_USERNAME: admin
      DB_PASSWORD: postgres
      DB_NAME: apigateway
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nginx-proxy