version: '3.3'

services:
  db:
    image: rg.fr-par.scw.cloud/db-registry-namespace/db:latest
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: postgres
      DB_NAME: apigateway
      DB_PORT: 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q" ]
      interval: 3s
      timeout: 5s
      retries: 5

  api_gateway:
    image: rg.fr-par.scw.cloud/gateway-service-registry-namespace/gateway:latest
    ports:
      - 8080:8080
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: postgres
      DB_NAME: apigateway
      DB_PORT: 5432
    depends_on:
      - db

  notes_service:
    image: rg.fr-par.scw.cloud/notes-service-registry-namespace/notes:latest
    ports:
      - 50053:50053
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: postgres
      DB_NAME: apigateway
      DB_PORT: 5432
    depends_on:
      - db

  users_service:
    image: rg.fr-par.scw.cloud/users-service-registry-namespace/users:latest
    ports:
      - 50052:50052
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: postgres
      DB_NAME: apigateway
      DB_PORT: 5432
    depends_on:
      - db

  permissions_service:
    image: rg.fr-par.scw.cloud/permissions-service-registry-namespace/permissions:latest
    ports:
      - 50054:50054
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: postgres
      DB_NAME: apigateway
      DB_PORT: 5432
    depends_on:
      - db