// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	Uuid      string
	Title     string
	Content   string
	CreatedBy pgtype.Text
}

type Permission struct {
	Uuid     string
	Service  string
	Resource string
	Action   string
}

type User struct {
	Uuid      string
	Email     string
	Password  string
	AuthToken string
}

type Userpermission struct {
	UserUuid       string
	PermissionUuid string
}
