---
- name: Setup Docker
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: Install curl
      ansible.builtin.apt:
        name: curl
        state: present
        update_cache: yes

    - name: Download Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Check Docker Compose version
      command: docker-compose --version
      register: result
      changed_when: False

    - name: Display Docker Compose version
      debug:
        var: result.stdout_lines

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Ensure docker service is running
      service:
        name: docker
        state: started
        enabled: yes

- name: Copy Docker-compose file to the server
  hosts: all
  become: true
  tasks:
    - name: Copy docker-compose file
      copy:
        src: ../../../docker-compose.yaml
        dest: ~/docker-compose.yaml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644