---
- name: Setup Certbot
  hosts: all
  become: true
  tasks:
    - name: Install Certbot and Nginx
      ansible.builtin.apt:
        name:
          - certbot
          - python3-certbot-nginx
          - nginx
        state: present

    - name: Obtain SSL Certificate
      command: certbot --nginx -d api.navyblueglove.uk -d www.api.navyblueglove.uk --non-interactive --agree-tos --email reda.maizate@gmail.com

    - name: Add cron job for automatic certificate renewal
      cron:
        name: "Certbot Auto Renewal"
        minute: "*/12"
        job: "certbot renew"