---
- name: Setup Docker
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Install dependencies
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg-agent

    - name: Add an apt signing key for Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-buildx-plugin

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ansible_user}}"
        group: docker

- name: Copy Docker-compose file to the server
  hosts: all
  become: true

  tasks:
  - name: Copy docker-compose file
    copy:
      src: ../../../docker-compose.yaml
      dest: ~/docker-compose.yaml
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0644