---
- name: Waiting until reachable
  hosts: all
  gather_facts: no  # Important
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:

    - name: Gather facts for the first time
      setup: