# Install docker on all hosts
---
- hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Ensure docker service is running
      service:
        name: docker
        state: started
        enabled: yes