---
- name: Wait until reachable
  hosts: all
  gather_facts: no  # Important
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:

    - name: Gather facts for the first time
      setup:

- name: Install docker
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Ensure docker service is running
      service:
        name: docker
        state: started
        enabled: yes

- name: Copy Docker-compose file to the server
  hosts: all
  become: true
  tasks:
    - name: Copy docker-compose file
      copy:
        src: ../../docker-compose.yaml
        dest: ~/docker-compose.yaml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644